# bot and api as seperate node entities in same container
# db connected in seperate container

version: "3"
services:
  api-bot:
    build: .
    links:
      - "db:mongo"

  db:
    image: "mongo"
    volumes:
      - db-data:/data/db

volumes:
  db-data:
